---
name: SenseAI
version: 0.5
slug: sense_ai
description: SenseAI
url: https://github.com/kdosiodjinud/homeassistant-integrations/homeassistant-sense-ai
codenotary: kdosiodjinud@gmail.com
startup: system
ingress: true
ingress_stream: true
host_network: true
panel_icon: mdi:dharmachakra
panel_title: SenseAI
panel_admin: false
init: false
arch:
  - amd64
ports:
  32168/tcp: 32168
  80/tcp: 80
watchdog: http://[HOST]:32168
