---
name: Agent DVR
version: 9.5
slug: agent_dvr
description: AgentDVR server
url: https://github.com/kdosiodjinud/homeassistant-agent-dvr
codenotary: kdosiodjinud@gmail.com
startup: system
ingress: true
ingress_port: 8090
ingress_stream: true
host_network: true
panel_icon: mdi:camera
panel_title: Kamery
panel_admin: false
init: false
arch:
  - amd64
ports:
  8090/tcp: 8090
watchdog: http://[HOST]:8090/logs.html
backup_exclude:
  - /AgentDVR/Media/WebServerRoot/Media/
  - /data/Media/WebServerRoot/Media/
