---
name: Agent DVR
version: 10.2
slug: agent_dvr
description: AgentDVR server
url: https://github.com/kdosiodjinud/homeassistant-agent-dvr
codenotary: kdosiodjinud@gmail.com
startup: system
ingress: true
ingress_port: 8090
ingress_stream: true
host_network: true
panel_icon: mdi:camera
panel_title: Kamery
panel_admin: false
init: false
arch:
  - amd64
ports:
  8090/tcp: 8090
  3478/udp: 3478
  50000/udp: 50000
  50001/udp: 50001
  50002/udp: 50002
  50003/udp: 50003
  50004/udp: 50004
  50005/udp: 50005
  50006/udp: 50006
  50007/udp: 50007
  50008/udp: 50008
  50009/udp: 50009
  50010/udp: 50010
watchdog: http://[HOST]:8090/logs.html
backup_exclude:
  - /AgentDVR/Media/WebServerRoot/Media/
  - /data/Media/WebServerRoot/Media/
