---
name: Agent DVR
version: 4.7
slug: agent_dvr
description: AgentDVR server
url: https://github.com/kdosiodjinud/homeassistant-agent-dvr
codenotary: kdosiodjinud@gmail.com
startup: system
ingress: true
ingress_port: 8090
ingress_stream: true
host_network: true
panel_icon: mdi:camera
panel_title: Kamery
panel_admin: false
arch:
  - amd64
ports:
  8090/tcp: 8090
