---
name: Flight Extractor
version: 0.1.0
slug: flight_extractor
description: Mock flight data extractor
url: https://github.com/kdosiodjinud/homeassistant-addons/flight-extractor
codenotary: kdosiodjinud@gmail.com
startup: system
init: false
arch:
  - amd64
host_network: true
ports:
  3000/tcp: 3000
