---
name: UniFi Network Controller
version: 0.0.1
slug: unifi_network_controller
description: UniFi Network Controller app
url: https://github.com/kdosiodjinud/homeassistant-addons/unifi-network-controller
codenotary: kdosiodjinud@gmail.com
startup: system
init: false
ingress: true
ingress_port: 8443
ingress_stream: false
host_network: true
panel_icon: mdi:camera
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
  8443/tcp: 8443
options:
  runners: []

